#!/usr/bin/env python3
"""Generate docs/albo-STATE.md from the builders themselves.

WHY THIS IS GENERATED. On 2026-09-21 a new session asking "what is the roman g
now?" would have been told the wrong thing twice by this repo's own index:
`albo-g-anatomy.md` is titled "The binocular g" and the roman stopped being
binocular at round 335, and `wedge-serif-exploration.md`'s STATE said
ALBO_G_STYLE defaults to `bent` when the code says `open`. Prose about defaults
goes stale silently, because nothing fails when it does. A file generated from
`os.environ.get(NAME, DEFAULT)` cannot be wrong about the thing it reads.

    python3 gen_state.py            # write ../../docs/albo-STATE.md
    python3 gen_state.py --check    # exit 1 if the file is out of date

An ARM is a dial whose default is a word rather than a number -- the switches
that decide which construction draws a letter. Those are what a reader almost
always wants, so they are listed first and in full; the numeric dials follow,
by file.
"""
import argparse, ast, os, re, subprocess, sys, datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
DOC = os.path.normpath(os.path.join(ROOT, "..", "..", "docs", "albo-STATE.md"))
PAT = re.compile(r'os\.environ\.get\(\s*["\'](ALBO_[A-Z0-9_]+|FJORD_[A-Z0-9_]+)["\']\s*,\s*([^)]+?)\s*\)')


def scan():
    arms, dials = [], []
    for dirpath, _, names in os.walk(os.path.join(ROOT, "outlines")):
        for n in sorted(names):
            if not n.endswith(".py"):
                continue
            p = os.path.join(dirpath, n)
            rel = os.path.relpath(p, ROOT)
            for i, line in enumerate(open(p, encoding="utf-8"), 1):
                m = PAT.search(line)
                if not m:
                    continue
                var, raw = m.group(1), m.group(2).strip()
                try:
                    val = ast.literal_eval(raw)
                except Exception:
                    val = raw
                row = (var, val, f"{rel}:{i}")
                (arms if isinstance(val, str) and val and not val[0].isdigit()
                 else dials).append(row)
    return arms, dials


def render():
    arms, dials = scan()
    try:
        head = subprocess.run(["git", "-C", ROOT, "log", "-1", "--format=%h %ad",
                               "--date=short"], capture_output=True, text=True).stdout.strip()
    except Exception:
        head = "?"
    L = []
    L.append("# Albo — what actually ships\n")
    L.append("**GENERATED by `tools/wedge_serif/gen_state.py`. Do not edit.**")
    L.append(f"Read from the builders' own defaults at `{head}`.\n")
    L.append("Prose docs carry the *history* and the reasoning and go stale about")
    L.append("defaults; this file is read from `os.environ.get(NAME, DEFAULT)` and")
    L.append("cannot be. If a doc disagrees with this table, this table is right.\n")
    L.append("## The arms — which construction draws each letter\n")
    L.append("| variable | ships | defined |")
    L.append("|---|---|---|")
    for v, val, where in sorted(arms):
        L.append(f"| `{v}` | **{val}** | `{where}` |")
    L.append(f"\n## The numeric dials ({len(dials)})\n")
    L.append("| variable | default | defined |")
    L.append("|---|---|---|")
    for v, val, where in sorted(dials):
        L.append(f"| `{v}` | {val} | `{where}` |")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    new = render()
    old = open(DOC, encoding="utf-8").read() if os.path.exists(DOC) else None
    if a.check:
        if old == new:
            print("albo-STATE.md is current"); return 0
        print("albo-STATE.md is OUT OF DATE — run `python3 gen_state.py`"); return 1
    open(DOC, "w", encoding="utf-8").write(new)
    arms = new.count("| **")
    print(f"wrote {os.path.relpath(DOC, ROOT)}  ({arms} arms)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
