#!/usr/bin/env python3
"""Regenerate cmake/CrossPointSources.cmake from a real PlatformIO build.

The simulator's stated failure mode is the HAL stub rule: the firmware adds a
method, the simulator fails to link until a stub matches it. On a fork you break
that continuously, so the CMake source set must never be hand-maintained -- it is
derived from the authoritative `compile_commands.json` that PlatformIO emits for
the env that already works.

Usage (from the firmware checkout):

    pio run -e simulator -t compiledb
    python3 <simulator>/tools/gen_cmake_sources.py \
        --firmware-dir . \
        --compile-db compile_commands.json

Defines that are PlatformIO's own bookkeeping (PLATFORMIO=) or come from the
host SDL2 pkg-config (_THREAD_SAFE) are dropped: the iOS toolchain supplies its
own, and baking the host's values in would be a lie about the build.

Nothing is written until every check in `validate` passes. That ordering is the
point of this script's guards: a half-written or empty source set is worse than
no run at all, because `cmake/CrossPointSources.cmake` is the ONLY thing telling
the iOS build which firmware sources to compile, and the resulting failure lands
hundreds of lines away from the cause -- or does not fail at all, and ships a
binary quietly missing whole features.
"""

import argparse
import json
import os
import re
import subprocess
import sys

# PlatformIO/host-toolchain bookkeeping, not part of the firmware's contract.
# CROSSPOINT_RENDER_SCALE is a PER-TARGET presentation choice, not a shared
# fact: the desktop env defaults it to 1 while ios/CMakeLists.txt sets 2.
# Harvesting it from the desktop compiledb plants a duplicate -D that fights
# the iOS target's value (this shipped a TestFlight build with 2x silently
# off). The consuming CMakeLists must set it explicitly.
DROP_DEFINE_PREFIXES = ("PLATFORMIO=", "_THREAD_SAFE", "CROSSPOINT_RENDER_SCALE=")

# A sanity floor, not a target. The real firmware set has been 125 TUs and has
# never been near three figures below that; every silent-failure mode this
# script guards against lands at 0 or a handful. Deliberately loose so a genuine
# upstream slim-down does not trip it -- the precise work is done by the
# under-firmware-dir and exists-on-disk checks, which cannot be fooled by a
# plausible count.
MIN_FIRMWARE_TUS = 64

HEADER = """# GENERATED by tools/gen_cmake_sources.py -- do not edit by hand.
#
# Source: PlatformIO env `simulator` of the CrossPoint firmware checkout, via
# `pio run -e simulator -t compiledb`. Regenerate after any firmware change that
# adds, removes, or renames a translation unit.
#
# firmware   : {fw_dir}
# pinned at  : {fw_sha}
# TU counts  : {n_fw} firmware, {n_sim} simulator ({n_c} C, {n_cxx} C++)

# The firmware commit this source set was generated from. Upstream restructures
# its tree frequently; a source list is only valid against the tree it was
# derived from, so CI builds this commit by default rather than a moving branch.
set(CROSSPOINT_FIRMWARE_PIN "{fw_sha}")
"""

# Appended to every fatal message. Naming the tree and the exact commands is the
# house style for guards here (see CMakeLists.txt's crosspoint_validate_sources
# and ios/testflight.sh's freshness gate): an error that only says what broke
# gets worked around, one that says why and how gets fixed.
REGENERATE_HINT = """
  Nothing was written -- the previous source set is untouched.

  Regenerate from the firmware checkout you actually mean to build. PlatformIO
  writes compile_commands.json into the checkout it ran in, and every worktree
  has its own, so the database and --firmware-dir must be the same tree:

    cd {fw_dir}
    git submodule update --init --recursive   # a bare worktree builds nothing
    pio run -e simulator -t compiledb
    python3 {script} \\
      --firmware-dir . --compile-db compile_commands.json"""


def firmware_sha(fw_root):
    try:
        return subprocess.run(
            ["git", "-C", fw_root, "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def rel(path, root):
    return os.path.relpath(os.path.realpath(path), os.path.realpath(root))


def entry_path(entry, path, fw_root):
    """Resolve one compile-db path the way the format specifies.

    `file` and the -I arguments are relative to the entry's own `directory`, NOT
    to this process's cwd -- PlatformIO emits `lib/Utf8/Utf8.cpp` with
    `directory` set to the firmware root. Resolving against cwd instead is the
    bug this whole guard rail exists for: run from the simulator repo, all 125
    firmware paths resolved under the SIMULATOR root, were filed as simulator
    sources, and CROSSPOINT_FW_SOURCES was written empty with exit status 0.
    os.path.join leaves an already-absolute `path` alone, so this handles both.
    """
    return os.path.realpath(os.path.join(entry.get("directory") or fw_root, path))


def emit_list(out, name, items, comment):
    out.append(f"\n# {comment}")
    out.append(f"set({name}")
    for item in items:
        out.append(f"  {item}")
    out.append(")")


def die(message, fw_root, script_path):
    sys.exit(
        "error: " + message.rstrip()
        + "\n" + REGENERATE_HINT.format(fw_dir=fw_root, script=script_path) + "\n"
    )


def collect(db, fw_root, sim_root):
    fw_sources, sim_sources = [], []
    defines, includes = set(), set()
    n_c = n_cxx = 0

    for entry in db:
        src = entry_path(entry, entry["file"], fw_root)
        if src.endswith(".c"):
            n_c += 1
        else:
            n_cxx += 1

        if src.startswith(sim_root + os.sep):
            sim_sources.append(rel(src, sim_root))
        else:
            fw_sources.append(rel(src, fw_root))

        tokens = entry.get("arguments") or entry["command"].split()
        for tok in tokens:
            if tok.startswith("-D"):
                value = tok[2:]
                if not value.startswith(DROP_DEFINE_PREFIXES):
                    defines.add(value)
            elif tok.startswith("-I"):
                inc_real = entry_path(entry, tok[2:], fw_root)
                if not os.path.isdir(inc_real):
                    continue
                # The simulator's own src/ and the host SDL headers are supplied
                # by the CMake targets, not by this list.
                if inc_real == os.path.join(sim_root, "src"):
                    continue
                if "SDL" in inc_real:
                    continue
                if inc_real.startswith(fw_root + os.sep) or inc_real == fw_root:
                    includes.add(rel(inc_real, fw_root))

    return sorted(set(fw_sources)), sorted(set(sim_sources)), sorted(includes), sorted(defines), n_c, n_cxx


def validate(db_path, n_entries, fw_root, sim_root, fw_sources, sim_sources, includes):
    """Return a fatal message, or None. Runs BEFORE anything is written."""
    where = (
        f"\n\n  compile db : {db_path} ({n_entries} entries)"
        f"\n  firmware   : {fw_root}"
        f"\n  simulator  : {sim_root}"
    )

    if not n_entries:
        return (
            "the compile database is empty." + where + "\n\n"
            "  `pio run -e simulator -t compiledb` exits 0 even when it compiled\n"
            "  nothing -- a fresh worktree whose freeink-sdk submodule was never\n"
            "  initialised does exactly that."
        )

    if not fw_sources:
        return (
            f"the compile database yielded 0 firmware translation units (healthy "
            f"is ~125)." + where + "\n\n"
            "  An empty CROSSPOINT_FW_SOURCES is not a smaller build, it is a\n"
            "  build that links nothing, and the failure surfaces far from here.\n\n"
            "  Every entry was classified as a SIMULATOR source, which happens when\n"
            "  the compile database's paths resolve under the simulator root instead\n"
            "  of the firmware one -- a database generated for a different tree than\n"
            "  --firmware-dir, or for a non-simulator env."
        )

    if not sim_sources:
        return (
            "no simulator sources in the compile database." + where + "\n\n"
            "  The firmware's [env:simulator] must consume THIS checkout, so its\n"
            "  lib_deps needs `simulator=symlink://" + sim_root + "` rather than the\n"
            "  upstream git URL; otherwise the HAL you are editing is not the HAL\n"
            "  that was compiled."
        )

    escaped = [p for p in fw_sources if p.startswith(os.pardir + os.sep)]
    if escaped:
        return (
            f"{len(escaped)} of {len(fw_sources)} firmware sources resolve OUTSIDE "
            "--firmware-dir." + where + "\n\n"
            "  CMake joins these onto CROSSPOINT_FIRMWARE_DIR, so a path that has to\n"
            "  climb out of the tree is never a real source. The compile database\n"
            "  describes a different checkout than the one passed here.\n\n"
            "  First few:\n    " + "\n    ".join(escaped[:5])
        )

    missing = [p for p in fw_sources if not os.path.exists(os.path.join(fw_root, p))]
    missing += [
        "(simulator) " + p
        for p in sim_sources
        if not os.path.exists(os.path.join(sim_root, p))
    ]
    if missing:
        return (
            f"{len(missing)} listed source(s) do not exist on disk." + where + "\n\n"
            "  A source set is only valid against the tree it was derived from. These\n"
            "  paths came out of the compile database but are not there now, so the\n"
            "  database is stale or belongs to another checkout.\n\n"
            "  First few:\n    " + "\n    ".join(missing[:5])
        )

    if len(fw_sources) < MIN_FIRMWARE_TUS:
        return (
            f"only {len(fw_sources)} firmware translation units (healthy is ~125, "
            f"floor is {MIN_FIRMWARE_TUS})." + where + "\n\n"
            "  Every path checks out, so this is a PARTIAL database rather than a\n"
            "  wrong one: an interrupted or incremental build, or an env that\n"
            "  compiles only part of the tree. Shipping it drops whole features from\n"
            "  the iOS binary without failing the build."
        )

    if not includes:
        return (
            "0 firmware include dirs." + where + "\n\n"
            "  The firmware cannot compile without its own -I set, so an empty\n"
            "  CROSSPOINT_FW_INCLUDE_DIRS means the database's -I paths did not\n"
            "  resolve against the firmware tree -- the same tree mismatch that\n"
            "  corrupts the source lists, caught on a different symptom."
        )

    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--firmware-dir", required=True)
    ap.add_argument("--compile-db", required=True)
    ap.add_argument(
        "--simulator-dir",
        default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    ap.add_argument("--output")
    args = ap.parse_args()

    script_path = os.path.abspath(__file__)
    fw_root = os.path.realpath(args.firmware_dir)
    sim_root = os.path.realpath(args.simulator_dir)
    out_path = args.output or os.path.join(
        sim_root, "cmake", "CrossPointSources.cmake"
    )

    if not os.path.isdir(fw_root):
        die(f"--firmware-dir is not a directory: {fw_root}", fw_root, script_path)

    db_path = os.path.realpath(args.compile_db)
    try:
        with open(db_path) as fh:
            db = json.load(fh)
    except OSError as exc:
        die(f"cannot read --compile-db: {exc}", fw_root, script_path)
    except json.JSONDecodeError as exc:
        die(f"--compile-db is not valid JSON ({db_path}): {exc}", fw_root, script_path)

    if not isinstance(db, list):
        die(
            f"--compile-db is not a JSON compilation database ({db_path}): expected a "
            f"list of entries, got {type(db).__name__}.",
            fw_root, script_path,
        )

    fw_sources, sim_sources, includes, defines, n_c, n_cxx = collect(
        db, fw_root, sim_root
    )

    problem = validate(
        db_path, len(db), fw_root, sim_root, fw_sources, sim_sources, includes
    )
    if problem:
        die(problem, fw_root, script_path)

    out = [
        HEADER.format(
            fw_dir=fw_root,
            fw_sha=firmware_sha(fw_root),
            n_fw=len(fw_sources),
            n_sim=len(sim_sources),
            n_c=n_c,
            n_cxx=n_cxx,
        )
    ]
    emit_list(
        out,
        "CROSSPOINT_SIM_SOURCES",
        sim_sources,
        "Simulator HAL + Arduino/ESP-IDF shims. Paths relative to this repo root.",
    )
    emit_list(
        out,
        "CROSSPOINT_FW_SOURCES",
        fw_sources,
        "Firmware TUs. Paths relative to CROSSPOINT_FIRMWARE_DIR.",
    )
    emit_list(
        out,
        "CROSSPOINT_FW_INCLUDE_DIRS",
        includes,
        "Firmware include dirs. Paths relative to CROSSPOINT_FIRMWARE_DIR.",
    )
    emit_list(
        out,
        "CROSSPOINT_DEFINES",
        defines,
        "Compile definitions, verbatim from the working desktop env.",
    )
    out.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(out))

    print(
        f"wrote {out_path}\n"
        f"  {len(fw_sources)} firmware TUs, {len(sim_sources)} simulator TUs\n"
        f"  {len(includes)} firmware include dirs, {len(defines)} defines"
    )

    check_ios_exclusions(sim_root, sim_sources, fw_sources)


# The iOS exclusion lists live in a file this script does NOT write -- they are
# policy, not derived data, and an earlier version of them was lost precisely
# because they sat in the generated file. This script still cross-checks them,
# because an exclusion naming a TU that no longer exists is drift too: it silently
# stops excluding anything, and the root CMakeLists.txt cannot tell the difference
# between "already absent" and "never matched".
def check_ios_exclusions(sim_root, sim_sources, fw_sources):
    path = os.path.join(sim_root, "cmake", "CrossPointIOSExclusions.cmake")
    try:
        text = open(path).read()
    except OSError:
        print(f"  WARNING: {path} not found; iOS builds will fail their exclusion check")
        return

    listed = re.findall(r"^\s*(src/\S+\.(?:cpp|c))\s*$", text, re.MULTILINE)
    known = set(sim_sources) | set(fw_sources)
    stale = [p for p in listed if p not in known]

    if stale:
        print(
            f"  WARNING: {len(stale)} iOS exclusion(s) match no TU in the new source set.\n"
            "           They exclude nothing. Update cmake/CrossPointIOSExclusions.cmake:"
        )
        for p in stale:
            print(f"             {p}")
    else:
        print(f"  {len(listed)} iOS exclusions all resolve")


if __name__ == "__main__":
    main()
