#!/usr/bin/env python3
"""Regenerate cmake/CrossPointSources.cmake from a real PlatformIO build.

The simulator's stated failure mode is the HAL stub rule: the firmware adds a
method, the simulator fails to link until a stub matches it. On a fork you break
that continuously, so the CMake source set must never be hand-maintained -- it is
derived from the authoritative `compile_commands.json` that PlatformIO emits for
the env that already works.

Usage (from the firmware checkout):

    pio run -e simulator -t compiledb
    python3 <simulator>/tools/gen_cmake_sources.py \
        --firmware-dir . \
        --compile-db compile_commands.json

Defines that are PlatformIO's own bookkeeping (PLATFORMIO=) or come from the
host SDL2 pkg-config (_THREAD_SAFE) are dropped: the iOS toolchain supplies its
own, and baking the host's values in would be a lie about the build.
"""

import argparse
import json
import os
import re
import subprocess
import sys

# PlatformIO/host-toolchain bookkeeping, not part of the firmware's contract.
# CROSSPOINT_RENDER_SCALE is a PER-TARGET presentation choice, not a shared
# fact: the desktop env defaults it to 1 while ios/CMakeLists.txt sets 2.
# Harvesting it from the desktop compiledb plants a duplicate -D that fights
# the iOS target's value (this shipped a TestFlight build with 2x silently
# off). The consuming CMakeLists must set it explicitly.
DROP_DEFINE_PREFIXES = ("PLATFORMIO=", "_THREAD_SAFE", "CROSSPOINT_RENDER_SCALE=")

HEADER = """# GENERATED by tools/gen_cmake_sources.py -- do not edit by hand.
#
# Source: PlatformIO env `simulator` of the CrossPoint firmware checkout, via
# `pio run -e simulator -t compiledb`. Regenerate after any firmware change that
# adds, removes, or renames a translation unit.
#
# firmware   : {fw_dir}
# pinned at  : {fw_sha}
# TU counts  : {n_fw} firmware, {n_sim} simulator ({n_c} C, {n_cxx} C++)

# The firmware commit this source set was generated from. Upstream restructures
# its tree frequently; a source list is only valid against the tree it was
# derived from, so CI builds this commit by default rather than a moving branch.
set(CROSSPOINT_FIRMWARE_PIN "{fw_sha}")
"""


def firmware_sha(fw_root):
    try:
        return subprocess.run(
            ["git", "-C", fw_root, "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


def rel(path, root):
    return os.path.relpath(os.path.realpath(path), os.path.realpath(root))


def emit_list(out, name, items, comment):
    out.append(f"\n# {comment}")
    out.append(f"set({name}")
    for item in items:
        out.append(f"  {item}")
    out.append(")")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--firmware-dir", required=True)
    ap.add_argument("--compile-db", required=True)
    ap.add_argument(
        "--simulator-dir",
        default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    ap.add_argument("--output")
    args = ap.parse_args()

    fw_root = os.path.realpath(args.firmware_dir)
    sim_root = os.path.realpath(args.simulator_dir)
    out_path = args.output or os.path.join(
        sim_root, "cmake", "CrossPointSources.cmake"
    )

    db = json.load(open(args.compile_db))

    fw_sources, sim_sources = [], []
    defines, includes = set(), set()
    n_c = n_cxx = 0

    for entry in db:
        src = os.path.realpath(entry["file"])
        if src.endswith(".c"):
            n_c += 1
        else:
            n_cxx += 1

        if src.startswith(sim_root + os.sep):
            sim_sources.append(rel(src, sim_root))
        else:
            fw_sources.append(rel(src, fw_root))

        tokens = entry.get("arguments") or entry["command"].split()
        for tok in tokens:
            if tok.startswith("-D"):
                value = tok[2:]
                if not value.startswith(DROP_DEFINE_PREFIXES):
                    defines.add(value)
            elif tok.startswith("-I"):
                inc = tok[2:]
                if not os.path.isdir(inc):
                    continue
                inc_real = os.path.realpath(inc)
                # The simulator's own src/ and the host SDL headers are supplied
                # by the CMake targets, not by this list.
                if inc_real == os.path.join(sim_root, "src"):
                    continue
                if "SDL" in inc_real:
                    continue
                if inc_real.startswith(fw_root + os.sep) or inc_real == fw_root:
                    includes.add(rel(inc_real, fw_root))

    fw_sources = sorted(set(fw_sources))
    sim_sources = sorted(set(sim_sources))

    if not sim_sources:
        sys.exit(
            "error: no simulator sources in the compile DB. Is the firmware's "
            "lib_deps pointing at this checkout via symlink:// ?"
        )

    out = [
        HEADER.format(
            fw_dir=fw_root,
            fw_sha=firmware_sha(fw_root),
            n_fw=len(fw_sources),
            n_sim=len(sim_sources),
            n_c=n_c,
            n_cxx=n_cxx,
        )
    ]
    emit_list(
        out,
        "CROSSPOINT_SIM_SOURCES",
        sim_sources,
        "Simulator HAL + Arduino/ESP-IDF shims. Paths relative to this repo root.",
    )
    emit_list(
        out,
        "CROSSPOINT_FW_SOURCES",
        fw_sources,
        "Firmware TUs. Paths relative to CROSSPOINT_FIRMWARE_DIR.",
    )
    emit_list(
        out,
        "CROSSPOINT_FW_INCLUDE_DIRS",
        sorted(includes),
        "Firmware include dirs. Paths relative to CROSSPOINT_FIRMWARE_DIR.",
    )
    emit_list(
        out,
        "CROSSPOINT_DEFINES",
        sorted(defines),
        "Compile definitions, verbatim from the working desktop env.",
    )
    out.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as fh:
        fh.write("\n".join(out))

    print(
        f"wrote {out_path}\n"
        f"  {len(fw_sources)} firmware TUs, {len(sim_sources)} simulator TUs\n"
        f"  {len(includes)} firmware include dirs, {len(defines)} defines"
    )

    check_ios_exclusions(sim_root, sim_sources, fw_sources)


# The iOS exclusion lists live in a file this script does NOT write -- they are
# policy, not derived data, and an earlier version of them was lost precisely
# because they sat in the generated file. This script still cross-checks them,
# because an exclusion naming a TU that no longer exists is drift too: it silently
# stops excluding anything, and the root CMakeLists.txt cannot tell the difference
# between "already absent" and "never matched".
def check_ios_exclusions(sim_root, sim_sources, fw_sources):
    path = os.path.join(sim_root, "cmake", "CrossPointIOSExclusions.cmake")
    try:
        text = open(path).read()
    except OSError:
        print(f"  WARNING: {path} not found; iOS builds will fail their exclusion check")
        return

    listed = re.findall(r"^\s*(src/\S+\.(?:cpp|c))\s*$", text, re.MULTILINE)
    known = set(sim_sources) | set(fw_sources)
    stale = [p for p in listed if p not in known]

    if stale:
        print(
            f"  WARNING: {len(stale)} iOS exclusion(s) match no TU in the new source set.\n"
            "           They exclude nothing. Update cmake/CrossPointIOSExclusions.cmake:"
        )
        for p in stale:
            print(f"             {p}")
    else:
        print(f"  {len(listed)} iOS exclusions all resolve")


if __name__ == "__main__":
    main()
