#pragma once

// Host screen-sleep control, for the one case where the firmware's idea of
// "idle" and the phone's disagree.
//
// A file transfer is minutes of the firmware doing nothing visible while a peer
// pushes books over the network. To iOS that is an idle app, so the screen locks
// and the app is suspended -- which stops the listening socket accepting and
// kills the transfer partway through. During QA that reads as a firmware bug in
// the web server, which is exactly the wrong conclusion to hand someone.
//
// A free hook rather than a HalDisplay method, for the same reason as
// SimulatorOverlay.h: real hardware has no analog, so it must not appear on a
// surface that mirrors the firmware's HAL. Everywhere but iOS it compiles to
// nothing.

#if defined(__APPLE__)
#include <TargetConditionals.h>
#endif

#ifndef CROSSPOINT_SIM_HOST_SCREEN
#if defined(__APPLE__) && TARGET_OS_IPHONE
#define CROSSPOINT_SIM_HOST_SCREEN 1
#else
#define CROSSPOINT_SIM_HOST_SCREEN 0
#endif
#endif

namespace sim_host_screen {

#if CROSSPOINT_SIM_HOST_SCREEN
// Safe to call from any thread; the platform hop to the main thread, which
// UIKit requires, happens inside. Reference-free: the last call wins, so a
// server that fails to start must still pass false on its way out.
void setKeepAwake(bool keepAwake);

// WHAT THIS DISPLAY CAN ACTUALLY DO, in frames per second.
//
// UIScreen.maximumFramesPerSecond is the authority and nothing else is. Owner
// directive 2026-08-26 was "enable 120hz if possible on iphone air", and the
// honest answer to "if possible" is a number read off the device rather than a
// model name in a table or a plist key that may be declaring something the
// panel cannot do. A ProMotion phone answers 120; everything else answers 60,
// and the Simulator answers whatever the host Mac's display does -- which is
// itself a reason to log it, since a 120 Hz reading on a Studio Display proves
// nothing about a phone.
//
// The plist key is the OTHER half and neither works alone: without
// CADisableMinimumFrameDuration iOS clamps every app to 60 whatever the panel
// is, and with it on a 60 Hz panel nothing changes. Reported at boot beside the
// [BUILD] identity line so a log always says which of those two states a run
// was in. Main thread.
int maximumFramesPerSecond();

// Whether this build DECLARED that it may exceed 60 Hz --
// CADisableMinimumFrameDuration in the bundle's own Info.plist, read back
// rather than assumed, because the key is generated by CMake and a template
// that stopped emitting it would otherwise fail silently and invisibly.
bool highFrameRateDeclared();
#else
inline void setKeepAwake(bool) {}
inline int maximumFramesPerSecond() { return 0; }
inline bool highFrameRateDeclared() { return false; }
#endif

}  // namespace sim_host_screen
