"""GENERATED by instruments/stem_axis_marks.py --write -- do not edit by hand.

Round 453 (2026-09-30). The italic references' optical offsets against the stem axis
(each letter's stems continued up on their own slope), in x-heights, + = right:
B per base letter (median over the symmetric marks, then over the fonts); M the acute's,
grave's and double acute's own lean, net of B, by case. References: texgyrepagella-italic.otf, coelacanth-italic.otf, Georgia Italic.ttf, Times New Roman Italic.ttf, flanker-griffo-italic.otf.
"""

B = {'A': 0.066, 'C': 0.086, 'E': -0.144, 'G': 0.058, 'I': -0.018, 'N': -0.01, 'O': 0.006, 'R': -0.157, 'S': -0.064, 'U': 0.003, 'Z': -0.06, 'a': 0.042, 'c': 0.016, 'e': 0.004, 'g': -0.024, 'i': -0.032, 'n': -0.039, 'o': -0.023, 'r': -0.054, 's': -0.064, 'u': -0.036, 'z': -0.086}

M = {'acute.lc': 0.041, 'acute.uc': 0.057, 'grave.lc': -0.063, 'grave.uc': -0.097, 'dblacute.lc': 0.079, 'dblacute.uc': 0.107}
